name: Deploy to Heroku
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Use Yarn
        run: npm install -g yarn@latest
      - name: Generate Config File
        env:
          BEAM_AUTH_TOKEN: ${{ secrets.BEAM_AUTH_TOKEN }}
          BEAM_APP_ID: ${{ secrets.BEAM_APP_ID }}
        run: ./.github/workflows/scripts/generateConfigFile.sh
      - name: Install dependencies
        working-directory: ./ui
        run: yarn install
      - name: Build
        working-directory: ./ui
        run: yarn build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "sdplat-feat"
          heroku_email: "andres.rovira@gmail.com"
